# SwiftLint Configuration for DynamicPinning iOS SDK

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Examples

# Rules
disabled_rules:
  - todo
  - trailing_whitespace
  
opt_in_rules:
  - empty_count
  - explicit_init
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - strict_fileprivate
  - force_unwrapping
  - implicitly_unwrapped_optional
  - non_optional_string_data_conversion

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 2

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - ttl
    - i

type_name:
  min_length: 3
  max_length: 50

# Allow some violations in tests (not production code)
force_unwrapping:
  severity: warning

implicitly_unwrapped_optional:
  severity: warning

non_optional_string_data_conversion:
  severity: warning

# Reporter
reporter: "xcode"

